apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaufen-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaufen-api
  template:
    metadata:
      labels:
        app: kaufen-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: kaufen-api
        image: kfile.azurecr.io/ki
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: kaufen-api
spec:
  type: LoadBalancer
  ports:
  - port: 50
    targetPort: 5000
  selector:
    app: kaufen-api